### ISSUE TITLE
Standardise and provide a setting to consistently style input placeholders

### ISSUE THREAD

**Issue by stowball** [chris-pearce/scally#117]
All browsers behave slightly differently with their placeholder colours, and Firefox reduces the opacity to 0.54 by default.

It would be great for Scally to help standardise this [like Suzi does](https://github.com/stowball/Suzi/blob/master/css/core/_mixins.scss#L729).

We'd need to set FF's opacity to 1, and provide a default colour var that all browsers used, which could easily be override by the developer like other settings. Something like this:

``` scss
$text-input-placeholder-color: rgba($colour-text-base, 0.4) !default;

:-moz-placeholder {
  color: $text-input-placeholder-color;
  opacity: 1;
}

::-moz-placeholder {
  color: $text-input-placeholder-color;
  opacity: 1;
 }

:-ms-input-placeholder {
  color: $text-input-placeholder-color;
 }

::-webkit-input-placeholder {
  color: $text-input-placeholder-color;
}
```
