### ISSUE TITLE
A space exists between the line-height value and the semi-colon in the font-size() mixin when compiled with LibSass

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#177]
E.g.

``` scss
.foobar {
  font-size: 1.4rem;
  line-height: 1.4 ;
}
```
