### ISSUE TITLE
Remove unneeded code from convert-px-to-em() function

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/scally#180]
This shouldn’t be there:

``` scss
  // If value is a named breakpoint
  @if type-of($value) == "string" {
    @if map-has-key($breakpoints, $value) {
      $value: map-get($breakpoints, $value);
    }
    @else {
      @warn "Breakpoint name '#{$value}' not recognised.";
    }
  }
```
